###  开发环境配置
server:
  #端口
  port: 8083
spring:
  ## profiles: dev
  #redis配置
  redis:
      database: 6
      host: 127.0.0.1
      port: 6379
      password: root      # 密码（默认为空）
      timeout: 6000ms  # 连接超时时长（毫秒）
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  # 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/elephant?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true
    username: root
    password: root

#日志
logging:
  config: classpath:log/logback.xml
  path: ./elephant

#自定义配置属性
#源码生成文件夹
source-code-dic:  D://mysite
source-code-zipfile:  D://源码.rar

#搜索文件生成包的位置
#本地路径
lucence-dic: ./lucence


